export const CATEGORY_ORDER = [
  {
    id: "milk-tea",
    name: "奶茶",
    description: "今天要不要来一杯甜甜的。",
  },
  {
    id: "dessert",
    name: "蛋糕甜品",
    description: "蛋糕、小甜品、奶油都安排上。",
  },
  {
    id: "takeout",
    name: "外卖正餐",
    description: "想吃正经一顿的时候点这里。",
  },
  {
    id: "beef",
    name: "牛肉大餐",
    description: "吃牛肉这个单独给到牌面。",
  },
  {
    id: "snack",
    name: "零食宵夜",
    description: "晚上嘴馋的时候可以随便点。",
  },
  {
    id: "gift",
    name: "礼物惊喜",
    description: "不一定能吃，但值得开心。",
  },
];

export const MENU_ITEMS = [
  {
    id: "milk-tea-1",
    category: "milk-tea",
    name: "杨枝甘露冰冰茶",
    tag: "人气",
    description: "酸甜一点，不容易踩雷。",
    image: "",
  },
  {
    id: "milk-tea-2",
    category: "milk-tea",
    name: "芋泥啵啵厚牛乳",
    tag: "必点",
    description: "想喝绵密口感就选这个。",
    image: "",
  },
  {
    id: "milk-tea-3",
    category: "milk-tea",
    name: "茉莉轻乳茶",
    tag: "清爽",
    description: "不想太腻的时候很适合。",
    image: "",
  },
  {
    id: "dessert-1",
    category: "dessert",
    name: "草莓奶油小蛋糕",
    tag: "甜甜",
    description: "适合庆祝，也适合随便开心一下。",
    image: "",
  },
  {
    id: "dessert-2",
    category: "dessert",
    name: "巴斯克流心芝士",
    tag: "浓郁",
    description: "偏重口一点，适合芝士脑袋。",
    image: "",
  },
  {
    id: "dessert-3",
    category: "dessert",
    name: "提拉米苏杯",
    tag: "下午茶",
    description: "一人份刚刚好，吃起来没负担。",
    image: "",
  },
  {
    id: "takeout-1",
    category: "takeout",
    name: "番茄肥牛饭",
    tag: "稳妥",
    description: "热乎乎的一碗，出错概率低。",
    image: "",
  },
  {
    id: "takeout-2",
    category: "takeout",
    name: "香辣鸡腿意面",
    tag: "满足",
    description: "偏香一点，适合想吃饱。",
    image: "",
  },
  {
    id: "takeout-3",
    category: "takeout",
    name: "鳗鱼滑蛋盖饭",
    tag: "加餐",
    description: "看起来就像认真宠一下。",
    image: "",
  },
  {
    id: "beef-1",
    category: "beef",
    name: "黑椒牛排套餐",
    tag: "主推",
    description: "牛肉单开一类，仪式感拉满。",
    image: "",
  },
  {
    id: "beef-2",
    category: "beef",
    name: "寿喜锅肥牛拼盘",
    tag: "热乎",
    description: "适合天气凉一点的时候点。",
    image: "",
  },
  {
    id: "beef-3",
    category: "beef",
    name: "蒜香煎牛小排",
    tag: "奖励自己",
    description: "想吃好一点的时候选它。",
    image: "",
  },
  {
    id: "snack-1",
    category: "snack",
    name: "芝士薯条",
    tag: "追剧",
    description: "边看边吃最方便。",
    image: "",
  },
  {
    id: "snack-2",
    category: "snack",
    name: "炸鸡翅小份",
    tag: "快乐",
    description: "很适合突然嘴馋。",
    image: "",
  },
  {
    id: "snack-3",
    category: "snack",
    name: "焦糖爆米花桶",
    tag: "分享",
    description: "可以慢慢吃，也适合看电影。",
    image: "",
  },
  {
    id: "gift-1",
    category: "gift",
    name: "一束淡粉小花",
    tag: "惊喜",
    description: "不一定贵，但一定像认真准备过。",
    image: "",
  },
  {
    id: "gift-2",
    category: "gift",
    name: "香薰蜡烛礼盒",
    tag: "温柔",
    description: "适合想让生活有点氛围感。",
    image: "",
  },
  {
    id: "gift-3",
    category: "gift",
    name: "小挂件盲盒",
    tag: "可爱",
    description: "轻一点的小礼物，适合临时心动。",
    image: "",
  },
];

export const MENU_LOOKUP = new Map(MENU_ITEMS.map((item) => [item.id, item]));
export const CATEGORY_LOOKUP = new Map(CATEGORY_ORDER.map((item) => [item.id, item]));
