export const CATEGORY_ORDER = [
  {
    id: "takeout",
    name: "外卖",
    description: "主食和正餐都放这里。",
  },
  {
    id: "gift",
    name: "礼物",
    description: "想收点惊喜可以点这里。",
  },
  {
    id: "daily",
    name: "生活用品",
    description: "日常要用的慢慢补齐。",
  },
  {
    id: "drink",
    name: "饮品",
    description: "奶茶咖啡果茶都可以。",
  },
  {
    id: "dessert",
    name: "甜品零食",
    description: "嘴馋的时候随便加一点。",
  },
  {
    id: "other",
    name: "其他",
    description: "先留给临时想到的东西。",
  },
];

export const MENU_ITEMS = [
  {
    id: "takeout-1",
    category: "takeout",
    name: "面条",
    tag: "常点",
    description: "想吃热乎一点的时候可以选。",
    image: "./assets/yier/微信图片_20260429024206_5_3.jpg",
  },
  {
    id: "takeout-2",
    category: "takeout",
    name: "米饭",
    tag: "稳妥",
    description: "比较顶饱，也比较好选。",
    image: "./assets/yier/微信图片_20260429024207_6_3.jpg",
  },
  {
    id: "takeout-3",
    category: "takeout",
    name: "小吃",
    tag: "加餐",
    description: "想顺手多点一点就放这里。",
    image: "./assets/yier/微信图片_20260429024207_7_3.jpg",
  },
  {
    id: "gift-1",
    category: "gift",
    name: "鲜花",
    tag: "惊喜",
    description: "最常见也最不容易出错。",
    image: "./assets/yier/微信图片_20260429024208_8_3.jpg",
  },
  {
    id: "gift-2",
    category: "gift",
    name: "饰品",
    tag: "好看",
    description: "轻一点的小礼物也很合适。",
    image: "./assets/yier/微信图片_20260429024209_9_3.jpg",
  },
  {
    id: "gift-3",
    category: "gift",
    name: "礼盒",
    tag: "认真",
    description: "适合需要一点仪式感的时候。",
    image: "./assets/yier/微信图片_20260429024210_10_3.jpg",
  },
  {
    id: "daily-1",
    category: "daily",
    name: "纸巾",
    tag: "常备",
    description: "随手就会用到，补货最实在。",
    image: "./assets/yier/微信图片_20260429024210_11_3.jpg",
  },
  {
    id: "daily-2",
    category: "daily",
    name: "洗护",
    tag: "日常",
    description: "平时会反复买的那种。",
    image: "./assets/yier/微信图片_20260429024211_12_3.jpg",
  },
  {
    id: "daily-3",
    category: "daily",
    name: "清洁用品",
    tag: "补货",
    description: "家里缺了就顺手加进来。",
    image: "./assets/yier/微信图片_20260429024212_13_3.jpg",
  },
  {
    id: "drink-1",
    category: "drink",
    name: "奶茶",
    tag: "常喝",
    description: "想喝甜一点的时候点这个。",
    image: "./assets/yier/微信图片_20260429024212_14_3.jpg",
  },
  {
    id: "drink-2",
    category: "drink",
    name: "咖啡",
    tag: "提神",
    description: "工作学习的时候更实用一点。",
    image: "./assets/yier/微信图片_20260429024213_15_3.jpg",
  },
  {
    id: "drink-3",
    category: "drink",
    name: "果茶",
    tag: "清爽",
    description: "不想太腻的时候可以选。",
    image: "./assets/yier/微信图片_20260429024213_16_3.jpg",
  },
  {
    id: "dessert-1",
    category: "dessert",
    name: "蛋糕",
    tag: "甜甜",
    description: "想吃点甜的就放这个。",
    image: "./assets/yier/微信图片_20260429024214_17_3.jpg",
  },
  {
    id: "dessert-2",
    category: "dessert",
    name: "饼干",
    tag: "囤着",
    description: "嘴馋的时候随手就能吃。",
    image: "./assets/yier/微信图片_20260429024206_5_3.jpg",
  },
  {
    id: "dessert-3",
    category: "dessert",
    name: "糖果",
    tag: "小零嘴",
    description: "占地方不大，但很好加购。",
    image: "./assets/yier/微信图片_20260429024207_6_3.jpg",
  },
  {
    id: "other-1",
    category: "other",
    name: "文具",
    tag: "备用",
    description: "突然想到的小东西先放这里。",
    image: "./assets/yier/微信图片_20260429024207_7_3.jpg",
  },
  {
    id: "other-2",
    category: "other",
    name: "小家电",
    tag: "实用",
    description: "临时想到的需求可以放这类。",
    image: "./assets/yier/微信图片_20260429024208_8_3.jpg",
  },
  {
    id: "other-3",
    category: "other",
    name: "随便买点",
    tag: "待定",
    description: "先占个位置，之后再改也方便。",
    image: "./assets/yier/微信图片_20260429024209_9_3.jpg",
  },
];

export const MENU_LOOKUP = new Map(MENU_ITEMS.map((item) => [item.id, item]));
export const CATEGORY_LOOKUP = new Map(CATEGORY_ORDER.map((item) => [item.id, item]));
